### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by ShayBox** [jussi-kalliokoski/atom-npm-plus#7]
Add keybinds so i can do Shift + F9 to npm start :P

**Comment by jussi-kalliokoski** [comment]
I personally think keybinds should ship in separate packages (or, not ship at all :P) to avoid clashes - already had to disable keymaps for too many packages :D

**Comment by ShayBox** [comment]
then use atom's builtin keymap editor section and ship then as not set, and let users set them

**Comment by mrstux** [comment]
I would like to be able to add some keybinds, but a package would be a good idea
